### ISSUE TITLE
start a light node without any blockchain backend

### ISSUE THREAD

**Issue by acud** [ethersphere/bee-backlog#15]
With regards to the user onboarding milestone, we've concluded that one of the projects would be to be able to start a bee node without a chain backend at all, in order to allow for easier packaging. The task would consist of the following changes to the node bootstrapping:
- [x] no postage components started (at all)
- [x] no overlay verification
- [x] yes accounting, no settlements (only time-based "settlements")
- [x] ENS resolver

**Comment by anatollupacescu** [comment]
this issue has only one pending task (documentation PR in `bee-docs`) and it needs approval from @acud and preferably from Dan as well
