### ISSUE TITLE
Check what happens on Linux in terms of connectivity on wakeup

### ISSUE THREAD

**Issue by mrekucci** [ethersphere/bee-backlog#23]
- what signal is received after wakening up from sleep
- `isNetworkError` returns true when the network interface is being disabled: https://github.com/ethersphere/bee/blob/master/pkg/topology/kademlia/kademlia.go#L1626
- do we get notifications about disconnections from libp2p: https://github.com/ethersphere/bee/blob/master/pkg/topology/kademlia/kademlia.go#L1132
- is there a way to somehow safely assume whether the computer is connected to the network

**Comment by notanatol** [comment]
confirmed that on Linux the resume signal is syscall.SIGCONT (12)

**Comment by notanatol** [comment]
@mrekucci I've been looking into the last point, trying to asses if we are connected to a network. 
So basically there are two layer:
- We can asses whether there is a network interface with an `192.168.0.16/24` ip.
- We can asses whether the network interface is enabled by checking if it has an IPv6 address assigned.
- We can asses if we have access to the wider network by trying to resolve (or Dial) to an external host.

Not sure which one is the right way to go.

**Comment by notanatol** [comment]
not sure if the second point was a question, but I double checked.

if the network interface is down then the error returned is being successfully detected by `topology.isNetworkError`
