### ISSUE TITLE
Remove global pinning feature

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-backlog#29]
Related to https://github.com/ethersphere/bee/issues/2354

Currently the feature is broken and it was designed before postage stamps were implemented in Bee. It is also turned off by default and because of the crash the recovery part is not achievable with normal use of the API. This means that the code is dead for a while now.  Furthermore it seems that the original assumptions are no longer held regarding the use-case, the postage stamp use (or the lack of it) and the time needed for recovery (i.e. sending PSS messages on a real network).

After consideration we realised that it would be best to remove this feature from Bee for now and encourage 2nd layer implementations instead.

**Comment by istae** [comment]
PR https://github.com/ethersphere/bee/pull/2869
