### ISSUE TITLE
Changes necessary outside of the depth pkg:

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-backlog#33]

**Comment by agazso** [comment]
- [ ] batchstore to report storage radius to depth pkg
- [ ] batchstore to stop reporting reserve radius to kademlia
- [ ] change SubscribePeersChange(rename) to notify on depth change as well
- [ ] kademlia SetRadius changed to SetDepth (no longer uses reservestate radius, but storage depth from the new pkg
- [ ] localstore reserve size reporting functionality (if not already implemented)

**Comment by agazso** [comment]
- [x] batchstore to report storage radius to depth pkg
- [x] batchstore to stop reporting reserve radius to kademlia
- [x] change SubscribePeersChange(rename) to notify on depth change as well
- [x] kademlia SetRadius changed to SetDepth (no longer uses reservestate radius, but storage depth from the new pkg
- [ ] localstore reserve size reporting functionality (if not already implemented)

**Comment by istae** [comment]
PR: https://github.com/ethersphere/bee/pull/3055
