### ISSUE TITLE
Retrieval protocol is unreadable

### ISSUE THREAD

**Issue by acud** [ethersphere/bee-backlog#36]
It has too much nesting and its not even remotely possible to understand what's going on without wasting hours at a time.

Another big problem we saw is that the logging is confusing. e.g. we always log when a request is issued, but not always when we have an error. This led is to believe there's a problem with the protocol logic and we spend an hour just to see that the result is not always logged, however, looking at the logs we could see duplicate lines of requests, that suggested that there's a problem.

**Comment by AuHau** [comment]
I would maybe suggest having a look on the [Bee node bootstrapping](https://github.com/ethersphere/bee/blob/master/pkg/node/node.go) as well ;-) Having 900 lines function does not seem to me like the best

**Comment by acud** [comment]
PRs for improving the bootstrapper are welcome @AuHau. Also, I don't think the two are comparable in complexity. I'm sure you can understand how the bootstrapper works.

**Comment by agazso** [comment]
The idea here is that the research team could provide a written documentation about the components and their interaction and from that a proposal can be created.

**Comment by istae** [comment]
Fixed by https://github.com/ethersphere/bee/pull/3428
