### ISSUE TITLE
beekeeper CI integration tests are not providing sufficient coverage

### ISSUE THREAD

**Issue by istae** [ethersphere/bee-backlog#47]
We have several new endpoints that are not currently tested by the beekeeper checks.
Also, we should test multiple modes like light and ultra light nodes, being able to upload and download, and also responding to important endpoints.

**Comment by istae** [comment]
An example is staking

**Comment by umerm-work** [comment]
This can be close @istae as it is completed.  https://github.com/ethersphere/bee/issues/3602#issue-1467545782
