### ISSUE TITLE
Remove Debug API

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-backlog#48]
There Debug API endpoints are already duplicated on the Bee API. The next step is to deprecate the Debug API and remove it completely.

In order to do that first it needs to be communicated that this is going to happen with a possible timeline so whoever is still using the Debug API have time to change their code to use the Bee API instead.

**Comment by AuHau** [comment]
Btw. also our products needs to support it (from bee-js to end products). Which is something we have still not got around to work on it.

**Comment by istae** [comment]
closes https://github.com/ethersphere/bee-backlog/issues/48

**Comment by nikipapadatou** [comment]
Already handled by the merge of the APIs tasks
