### ISSUE TITLE
 nodes still have chunks in the counted reserves after the testnet was wiped clean by the expiration of all the batches

### ISSUE THREAD

**Issue by istae** [ethersphere/bee-backlog#49]
https://monitoring.testnet.ethswarm.org/d/Szc9zJUGk/localstore?orgId=1&from=1668024000000&to=1668027599000&var-namespace=testnet-storage&var-instance=All

**Comment by ldeffenb** [comment]
My three non-pinning testnet nodes have just over 13,000 chunks in each of them.
