### ISSUE TITLE
batches depth increase is not taken into account during migration 

### ISSUE THREAD

**Issue by istae** [ethersphere/bee-backlog#52]
Batches that have been diluted with the previous contract have been migrated with the original batch depth.
This causes a discrepancy between the stamp issuer and the batch in batchstore, causing stamp validation to fail when uploading and syncing chunks, specifically at this line

https://github.com/ethersphere/bee/blob/master/pkg/postage/stamp.go#L162

**Comment by mrekucci** [comment]
Fixed in https://github.com/ethersphere/batch-migration/pull/2
