### ISSUE TITLE
investigate upload errors of the smoke tests

### ISSUE THREAD

**Issue by istae** [ethersphere/bee-backlog#53]
We recently changed uploads on the smoke test to be direct. 
We are now seeing higher amount of upload errors.
https://monitoring.mainnet.ethswarm.org/d/R6nXBFH7k/milestone-smoke-test?orgId=1&refresh=30s&var-job=bee-gateway

**Comment by vladopajic** [comment]
Seems to be fixed after https://github.com/ethersphere/bee/pull/3903
