### ISSUE TITLE
mainnet batch creation minimum depth requirement

### ISSUE THREAD

**Issue by istae** [ethersphere/bee-backlog#58]
In order to improve batch utilization, the node should have some minimum depth requirement.
with a batch depth of something like 17 or 18, the batch runs out very quickly and unproportionally without filling most of the buckets available.
increasing depth improves utilization percentage.

Task:

1. investigate which minimum depth gives at least 50% utilization.
2. introduce the change in bee API

**Comment by nikipapadatou** [comment]
Input from the research team: If we need  a minimum 50% utilisation this is the following:
Depth 23 gives a theoretical 48% and 24 gives 60%

**Comment by istae** [comment]
it was agreed on 20/9/2023 that the minimum allowed batch depth in the API should be **24**.

**Comment by tmm360** [comment]
@istae does it mean that the minimum allocable space will be ~68.72 GB? If it's right, this looks more a bad workaround than a solution.
Have you already evaluated a solution like this? https://github.com/ethersphere/bee/issues/4292#issuecomment-1728568441

**Comment by istae** [comment]
with this new test https://github.com/ethersphere/bee/pull/4398
it was revelated that depth 22 can consistently provide > 50% utilization

**Comment by istae** [comment]
considering worst case scenarios, 24 gives better utilization, so it will remain 24
