### ISSUE TITLE
write some documentation about the tools the bee teams uses to monitor the mainnet 

### ISSUE THREAD

**Issue by istae** [ethersphere/bee-backlog#62]

**Comment by istae** [comment]
https://hackmd.io/BZIgWnGyRJGiKTrhFcFT9Q

**Comment by ldeffenb** [comment]
> https://hackmd.io/BZIgWnGyRJGiKTrhFcFT9Q

![image](https://github.com/ethersphere/bee-backlog/assets/5175026/a2bd22a4-1d81-4968-831d-107c790c9813)
