### ISSUE TITLE
reserve size discrepancy after many batch evictions

### ISSUE THREAD

**Issue by istae** [ethersphere/bee-backlog#64]
After increasing the postage price, a large amount of batches expired, causing the storage radius to drop from 4 to 0.
It was expected that after expirations finish, the reserve sizes should match across every node, but this was not the case for some nodes.

after restarting node 5, the reserve size remained to be the same.

![image](https://github.com/ethersphere/bee-backlog/assets/14264581/111e12d6-ace4-4fec-a3e4-75143a5d5819)

**Comment by istae** [comment]
after adding a new metric for counting chunks belonging to invalid/non-existing batches, it was revealed that there are chunks in the reserve with bad chunks
![image](https://github.com/ethersphere/bee-backlog/assets/14264581/327569f5-283d-4ced-b262-a0f9b5967d73)

**Comment by istae** [comment]
A worker was added to remove expired chunks directly here https://github.com/ethersphere/bee/pull/4391

**Comment by istae** [comment]
after the rest of the tickets under the epic, a major testing session will be carried out.
if the issue described above still persists, then, a new investigation is needed.

**Comment by nikipapadatou** [comment]
Leveldb transactions tasks are expected to bring improvements to this one as well. Re-evaluate after leveldb tasks are released.

**Comment by nikipapadatou** [comment]
Closing this as it was handled by the changes on 2.1.
