### ISSUE TITLE
large data upload and download observations/report

### ISSUE THREAD

**Issue by istae** [ethersphere/bee-backlog#65]

**Comment by nikipapadatou** [comment]
Have already synced with Crt regarding this. He will try to upload and download different size files on mainnet, get the times, cpu etc, and will get a report for all these.

So before starting working on this ticket, please sync with him in order to avoid duplicate stuff.

**Comment by istae** [comment]
https://hackmd.io/lwyXeOXESlqTjlaPWNxolA
