### ISSUE TITLE
write a techical task for the QA position

### ISSUE THREAD

**Issue by istae** [ethersphere/bee-backlog#69]
1. run a light node
2. write a smoke test for uploading and downloading data

**Comment by istae** [comment]
https://hackmd.io/-udfKwiBTIa1hU10ztJsEg

**Comment by ldeffenb** [comment]
Not cool to keep publishing hackmd.io links that that public cannot view.
![image](https://github.com/ethersphere/bee-backlog/assets/5175026/e8a22915-913f-4f23-8ca2-32e09b5e11d1)
